### ISSUE TITLE
Make TraceId/SpanId public

### ISSUE THREAD

**Issue by swASO** [DataDog/dd-trace-csharp#133]
**Is your feature request related to a problem? Please describe.**
i want to forward the traceId and spanId, but i cant acces them.
i saw in the source, the ids are public in the [`SpanContext`](https://github.com/DataDog/dd-trace-csharp/blob/master/src/Datadog.Trace/SpanContext.cs#L64) but the SpanContext isnt public in the [Span](https://github.com/DataDog/dd-trace-csharp/blob/master/src/Datadog.Trace/Span.cs#L64)
How can i access them ? 

**Describe the solution you'd like**
can Access the TraceId / SpanId of the current Span - scope

**Comment by lucaspimentel** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make TraceId/SpanId public](https://trello.com/c/MXgJ4z3z/1096-make-traceid-spanid-public)

**Comment by lucaspimentel** [comment]
@swASO: thanks for the feedback! This is something we need do to support distributed tracing. We might end up refactoring `SpanContext`, `Span`, `Scope`, and `TraceContext` a little as part of this change, too.
