### ISSUE TITLE
An error occured while sending traces to the agent

### ISSUE THREAD

**Issue by swASO** [DataDog/dd-trace-csharp#149]
**Describe the bug**
Sometimes, not everytime, we gettings the folling error message

> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.IO.IOException: The server returned an invalid or unrecognized response.
>    at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
>    --- End of inner exception stack trace ---
>    at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
>    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
>    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
>    at Datadog.Trace.Agent.Api.SendAsync[T](T value, Uri endpoint)

**To Reproduce**
dont know because its completly random :( 

**Runtime environment (please complete the following information):**
- Instrumentation mode: manual
- Tracer version: 0.3.0
- OS: Linux / Docker image ( microsoft/dotnet:2.1-runtime-deps-stretch-slim )
- CLR: .Net Core 2.1

**Additional context**
if possible, see request 167415 over dd support

i tried also to enable "isDebugEnabled" but i cant see any other logging messages ( using nlog )

**Comment by lucaspimentel** [comment]
@swASO: There was a serialization bug (#137) in 0.3.0 which could cause the Tracer Agent to reject a trace. Can you try 0.3.1 and see if it fixes the issue?

**Comment by swASO** [comment]
still the same problem

**Comment by lucaspimentel** [comment]
Thanks for trying! Can you check for error message in the Trace Agent's `trace-agent.log` logfile? It would help to know why it is rejecting traces.

**Comment by swASO** [comment]
Hi, we cant find any errors to the specific error time in the log file, any other ideas ?

**Comment by pgrm** [comment]
we just had the same issue, it happened around 22:55 and as you can see, there was something going on on our system at that time:

![image](https://user-images.githubusercontent.com/713456/47184528-30c3e880-d32b-11e8-8814-272b46643baa.png)

**Comment by dd-caleb** [comment]
The next version (0.4.1) will include a retry on trace submission to the local agent before showing this error.

**Comment by willyyang** [comment]
I have this same issue. Using 0.4.1-beta

**Comment by willyyang** [comment]
This issue should be re-opened.
