### ISSUE TITLE
An error occured on application exit

### ISSUE THREAD

**Issue by VladikAN** [DataDog/dd-trace-csharp#172]
**Describe the bug**
I'm working on Csharp application with Datadog integration. 
Then I terminating my app by using ctrl-c it will lead to following error:

Unhandled Exception: Syacstem.AggregateException: One or more errors occurred. (An attempt was made to transition a task to a final state when it had already completed.) ---> System.InvalidOperationException: An attempt was made to transition a task to a final state when it had already completed.
   at Datadog.Trace.Agent.AgentWriter.FlushAndCloseAsync()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Datadog.Trace.Tracer.CurrentDomain_UnhandledException(Object sender, UnhandledExceptionEventArgs e)

Looks like FlushAndCloseAsync will be called twice in this case:
1) Event for Console.CancelKeyPress inside of Tracer.cs.
2) Event for ProcessExitinside of Tracer.cs.

**To Reproduce**
1. Start console app.
2. Terminate by ctrl-c

**Runtime environment (please complete the following information):**
- Tracer version: 0.3.2
- OS: Windows 10
- CLR: .Net Core 2.1

**Comment by VladikAN** [comment]
And I'm using Microsoft.Extensions.Hosting with RunConsoleAsync(). Hope this helps

**Comment by dd-caleb** [comment]
(should be fixed in the next release, 0.4.1)
